name: Development

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build

  build_macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
